HomegeTown_MattTianaHouse_1F_MapScripts::
	.byte 0


HomegeTown_MattTianaHouse_1F_Mom::
# 4 "data/maps/HomegeTown_MattTianaHouse_1F/scripts.pory"
	lock
# 5 "data/maps/HomegeTown_MattTianaHouse_1F/scripts.pory"
	faceplayer
# 6 "data/maps/HomegeTown_MattTianaHouse_1F/scripts.pory"
	msgbox HomegeTown_MattTianaHouse_1F_Mom_Text_0
# 7 "data/maps/HomegeTown_MattTianaHouse_1F/scripts.pory"
	releaseall
	return


HomegeTown_MattTianaHouse_1F_Dad::
# 11 "data/maps/HomegeTown_MattTianaHouse_1F/scripts.pory"
	lock
# 12 "data/maps/HomegeTown_MattTianaHouse_1F/scripts.pory"
	faceplayer
# 13 "data/maps/HomegeTown_MattTianaHouse_1F/scripts.pory"
	msgbox HomegeTown_MattTianaHouse_1F_Dad_Text_0
# 14 "data/maps/HomegeTown_MattTianaHouse_1F/scripts.pory"
	releaseall
	return


HomegeTown_MattTianaHouse_1F_Mom_Text_0:
# 6 "data/maps/HomegeTown_MattTianaHouse_1F/scripts.pory"
	.string "We're so proud of our son!$"

HomegeTown_MattTianaHouse_1F_Dad_Text_0:
# 13 "data/maps/HomegeTown_MattTianaHouse_1F/scripts.pory"
	.string "Our son left a few months ago to start\n"
	.string "his Pokémon journey.\p"
	.string "Maybe you'll get to see him again when\n"
	.string "you start your adventure!$"
