IcovaleCity_House2_1F_MapScripts::
	.byte 0


IcovaleCity_House2_1F_GBKid::
# 4 "data/maps/IcovaleCity_House2_1F/scripts.pory"
	msgbox IcovaleCity_House2_1F_Text_Dreamsexual, MSGBOX_NPC
	end


IcovaleCity_House2_1F_BackInMyDay::
# 9 "data/maps/IcovaleCity_House2_1F/scripts.pory"
	msgbox IcovaleCity_House2_1F_Text_BackInMyDay, MSGBOX_NPC
	end


IcovaleCity_House2_1F_Text_Dreamsexual::
# 13 "data/maps/IcovaleCity_House2_1F/scripts.pory"
	.string "My sister upstairs keeps going on and\n"
	.string "on about how she's “dreamsexual.”\p"
	.string "…\p"
	.string "What does that even mean?$"

IcovaleCity_House2_1F_Text_BackInMyDay::
# 19 "data/maps/IcovaleCity_House2_1F/scripts.pory"
	.string "Back in my day, our town's architecture\n"
	.string "was a symbol of pride…\p"
	.string "…and Pokémon didn't have these\n"
	.string "newfangled scientific names either!\p"
	.string "My “Evecho” was named Hamilton, and he\n"
	.string "was grateful!$"
