IcovaleCity_Building1_1F_MapScripts::
	.byte 0


IcovaleCity_Building1_1F_UngratefulWife::
# 4 "data/maps/IcovaleCity_Building1_1F/scripts.pory"
	msgbox IcovaleCity_Building1_1F_UngratefulWife_Text_0, MSGBOX_NPC
	return


IcovaleCity_Building1_1F_CBDMan::
# 8 "data/maps/IcovaleCity_Building1_1F/scripts.pory"
	msgbox IcovaleCity_Building1_1F_CBDMan_Text_0, MSGBOX_NPC
	return


IcovaleCity_Building1_1F_UngratefulWife_Text_0:
# 4 "data/maps/IcovaleCity_Building1_1F/scripts.pory"
	.string "My husband is a complete moron.\p"
	.string "It's a miracle that he has a well-paying\n"
	.string "job and can afford a house like this.$"

IcovaleCity_Building1_1F_CBDMan_Text_0:
# 8 "data/maps/IcovaleCity_Building1_1F/scripts.pory"
	.string "Hey, I got some CBD, want a free sample?\p"
	.string "It has a lot of health benefits.\p"
	.string "One day, I couldn't make up my mind so I\n"
	.string "rubbed some on my forehead and I knew I\l"
	.string "wanted a sandwich right away.$"
