IcovaleCity_MapScripts::
	.byte 0


IcovaleCity_YoungsterFountain::
# 4 "data/maps/IcovaleCity/scripts.pory"
	msgbox IcovaleCity_YoungsterFountain_Text_0, MSGBOX_NPC
	return


IcovaleCity_MotherFountain::
# 8 "data/maps/IcovaleCity/scripts.pory"
	msgbox IcovaleCity_MotherFountain_Text_0, MSGBOX_NPC
	return


IcovaleCity_OldWomanFarmland::
# 12 "data/maps/IcovaleCity/scripts.pory"
	msgbox IcovaleCity_OldWomanFarmland_Text_0, MSGBOX_NPC
	return


IcovaleCity_BusinessMan::
# 16 "data/maps/IcovaleCity/scripts.pory"
	msgbox IcovaleCity_BusinessMan_Text_0, MSGBOX_NPC
	return


IcovaleCity_CitySign::
# 20 "data/maps/IcovaleCity/scripts.pory"
	msgbox IcovaleCity_CitySign_Text_0, MSGBOX_SIGN
	return


IcovaleCity_YoungsterFountain_Text_0:
# 4 "data/maps/IcovaleCity/scripts.pory"
	.string "I heard from meemaw that there used to\n"
	.string "be a giant Crimbark tree on this very\l"
	.string "spot!$"

IcovaleCity_MotherFountain_Text_0:
# 8 "data/maps/IcovaleCity/scripts.pory"
	.string "Mother told me as well that when they\n"
	.string "cut down the tree, it was enough to\l"
	.string "supply the wood for all the houses here\l"
	.string "back then!\p"
	.string "Back when the houses here were made of\n"
	.string "wood that is...$"

IcovaleCity_OldWomanFarmland_Text_0:
# 12 "data/maps/IcovaleCity/scripts.pory"
	.string "Things have changed around here. This\n"
	.string "was all farmland as far as the eye could\l"
	.string "see back then.$"

IcovaleCity_BusinessMan_Text_0:
# 16 "data/maps/IcovaleCity/scripts.pory"
	.string "Icovale has developed a lot over the\n"
	.string "years. Some of the old residents here\l"
	.string "disdain it though. It seems more plastic\l"
	.string "they say.\p"
	.string "I'm not sure what they're talking about!$"

IcovaleCity_CitySign_Text_0:
# 20 "data/maps/IcovaleCity/scripts.pory"
	.string "ICOVALE CITY\n"
	.string "“A new era of Vidioh!”$"
