IcovaleOffice_2F_MapScripts::
	.byte 0


IcovaleOffice_2F_CutCostPaperOnTable::
# 4 "data/maps/IcovaleOffice_2F/scripts.pory"
	msgbox IcovaleOffice_2F_CutCostPaperOnTable_Text_0, MSGBOX_SIGN
	return


IcovaleOffice_2F_TrickPaperOnTable::
# 8 "data/maps/IcovaleOffice_2F/scripts.pory"
	msgbox IcovaleOffice_2F_TrickPaperOnTable_Text_0, MSGBOX_SIGN
	return


IcovaleOffice_2F_FatMan::
# 12 "data/maps/IcovaleOffice_2F/scripts.pory"
	msgbox IcovaleOffice_2F_FatMan_Text_0, MSGBOX_NPC
	return


IcovaleOffice_2F_TrickEmployee::
# 16 "data/maps/IcovaleOffice_2F/scripts.pory"
	msgbox IcovaleOffice_2F_TrickEmployee_Text_0, MSGBOX_NPC
	return


IcovaleOffice_2F_OfficeIsLocked::
# 21 "data/maps/IcovaleOffice_2F/scripts.pory"
	msgbox IcovaleOffice_2F_OfficeIsLocked_Text_0, MSGBOX_SIGN
	return


IcovaleOffice_2F_CutCostPaperOnTable_Text_0:
# 4 "data/maps/IcovaleOffice_2F/scripts.pory"
	.string "It seems to be a plan to cut costs.$"

IcovaleOffice_2F_TrickPaperOnTable_Text_0:
# 8 "data/maps/IcovaleOffice_2F/scripts.pory"
	.string "It seems to be a plan to falsely\n"
	.string "reassure everyone that the company is\l"
	.string "doing okay.$"

IcovaleOffice_2F_FatMan_Text_0:
# 12 "data/maps/IcovaleOffice_2F/scripts.pory"
	.string "Welcome to the second floor. I'm working\n"
	.string "on cutting costs and which employees\l"
	.string "to layoff.$"

IcovaleOffice_2F_TrickEmployee_Text_0:
# 16 "data/maps/IcovaleOffice_2F/scripts.pory"
	.string "This company is bound to fall any day\n"
	.string "now. I'm not even entirely sure what\l"
	.string "we're selling.\p"
	.string "Lies, maybe.$"

IcovaleOffice_2F_OfficeIsLocked_Text_0:
# 21 "data/maps/IcovaleOffice_2F/scripts.pory"
	.string "The office door is locked.$"
