IcovaleOffice_2F_BROffice_MapScripts::
	.byte 0


IcovaleOffice_OldManNoPart::
# 4 "data/maps/IcovaleOffice_2F_BROffice/scripts.pory"
	msgbox IcovaleOffice_OldManNoPart_Text_0, MSGBOX_NPC
	return


IcovaleOffice_OldManNoPart_Text_0:
# 4 "data/maps/IcovaleOffice_2F_BROffice/scripts.pory"
	.string "I want no part of what's happening in\n"
	.string "that boardroom.\p"
	.string "Nothing good can come from it.$"
